#!/bin/sh

# sudo not required for some system commands
for command in mount umount pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}

# Verbosity and settings that you pretty much just always are going to want.
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias mkd="mkdir -pv"
alias ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"
alias ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias vd="vidir"
alias ka="killall"
alias g="git"
alias trem="transmission-remote"
alias YT="youtube-viewer"
alias sdn="shutdown -h now"
alias e="$EDITOR"
alias v="$EDITOR"
alias p="pacman"
alias xi="sudo xbps-install"
alias xu="sudo xbps-install -Syu"
alias xr="sudo xbps-remove -R"
alias xq="xbps-query"
alias xs="xbps-query -Rs"
alias z="zathura"
alias pg="pass git"
alias vr='/usr/bin/git --git-dir=$HOME/.local/src/voidrice --work-tree=$HOME'
alias ssv="sudo sv"

alias lf="lfub"
alias mg="nvim -c MagitOnly"
alias ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc"
alias weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport"
alias gfp="gcc -g -Wall -Wextra -pedantic"
