#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
export $(dbus-launch)
export PIPEWIRE_RUNTIME_DIR=$(mktemp -d)
export PULSE_RUNTIME_PATH="$PIPEWIRE_RUNTIME_DIR"

setxkbmap us,es,bg -variant ,,phonetic -option grp:lalt_lshift_toggle
xmodmap -e "keysym XF86WakeUp = Multi_key"
xset r rate 175 50
